version: 2.0
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: gradle assemble
      - run: gradle test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/distributions
          destination: distributions
      - store_artifacts:
          path: build/libs
          destination: libs
test:
  post:
    - mv $APP_HOME/build/reports/jacoco/jacocoTestReport $APP_HOME/build/reports/jacoco/test
    - cp -r $APP_HOME/build/outputs $CIRCLE_ARTIFACTS
    - cp -r $APP_HOME/build/reports $CIRCLE_ARTIFACTS
    - cp -r $APP_HOME/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS